baseurl: "/"
title: "R/Medicine"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-9232216-1"

params:
  # Conference info
  Name: "R/Medicine 2018"
  Description: "R/Medicine 2018"
  Date: "September 7-8"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "The Omni Hotel"
  Organizers: "Brought to you by the Yale School of Public Health Biostatistics Department and the R Consortium"
  Address: "155 Temple Street"
  City:  "New Haven"
  State: "CT"
  Images: ["/img/badge.jpg"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - keynotes
    - location
    - lodging
#    - schedule
    - sponsors
    - committee
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    keynotes: "Keynotes"
    lodging: "Lodging"
    location: "Location"
#    schedule: "Schedule"
    sponsors: "Sponsors"
    committee: "Committee"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
#  CallToAction1:
#    text: "Submit an Abstract"
#    link: "https://docs.google.com/forms/d/e/1FAIpQLSeJyzhA3N01Kj6bgdBz6pyjG7ztDR-iO8JFZhwm_Pf8mhYnhQ/viewform"
 
  CallToAction:
    text: "Click Here to Register"
    link: http://www.cvent.com/d/1gq0qx
 

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
#  ForkButton:
#    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
#  Sponsors:
#    - name: "Hugo"
#      logo: "/img/hugo.png"
#      url: "http://gohugo.io"
#
#  # List of Partners
#  Commitee:
#    - name: "Hugo"
#      logo: "/img/hugo.jpg"
#      url: "https://gohugo.io"
#    - name: "BrazilJS"
#      logo: "/img/partner.png"
#      url: "http://braziljs.org"
#

Keynotes:
    name: "Robert Tibshirani"
    link:
        href: "https://statweb.stanford.edu/~tibs/"

    name: "Victoria Stodden"
    link: 
        href: "https://ischool.illinois.edu/people/faculty/vcs"
        text: "@victoriastodden"

    name: "Michael Lawrence"
    link:
        href: "https://www.linkedin.com/in/michael-lawrence-74a9b482"
        text: "@lawremi"

  # The entire schedule
Schedule:
    - name: "Check-in / Breakfast"
      time: "9h00"

    - name: "Linus Torvalds"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Linux Foundation"
      link:
        href: "http://twitter.com/linus"
        text: "@linus"
      presentation:
        title: "Digging into a Linux Kernel"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "10h00"
#
#    - name: "Bill Gates"
#      photo: "/img/speaker.jpg"
#      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
#      company: "Microsoft"
#      link:
#        href: "http://github.com/billy95"
#        text: "@billy95"
#      presentation:
#        title: "Introducing Windows 12"
#        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
#        time: "11h00"
#
#    - name: "Lunch"
#      time: "12h00"
#
#    - name: "Chuck Norris"
#      photo: "/img/speaker.jpg"
#      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
#      company: "Delta Command"
#      link:
#        href: "http://twitter.com/littlechuck"
#        text: "@littlechuck"
#      presentation:
#        title: "How to kill a elephant with one finger"
#        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
#        time: "13h00"
#
#    - name: "Steve Jobs"
#      photo: "/img/speaker.jpg"
#      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
#      company: "Apple, Inc."
#      link:
#        href: "http://github.com/stevie"
#        text: "@stevie"
#      presentation:
#        title: "Presenting iPad"
#        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
#        time: "14h00"
#
#    - name: "Coffee-break"
#      time: "15h00"
#
#    - name: "Mark Zuckerberg"
#      photo: "/img/speaker.jpg"
#      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
#      company: "Facebook"
#      link:
#        href: "http://twitter.com/zuck"
#        text: "@zuck"
#      presentation:
#        title: "Revealing Facebook Secrets"
#        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
#        time: "16h00"
#
#    - name: "Steve Wozniak"
#      photo: "/img/speaker.jpg"
#      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
#      company: "Apple, Inc."
#      link:
#        href: "http://twitter.com/woz"
#        text: "@woz"
#      presentation:
#        title: "Why do I prefer Android over iPhone"
#        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
##        time: "17h00"
